version: '3.8'
services:
  mysql:
    container_name: contenedor1Mysql
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3307:3306"
volumes:
  mysql_data:
    driver: local